### ISSUE TITLE
AttributeError: can't set attribute 'split'

### ISSUE THREAD

**Issue by Jeremy-J-J** [modelscope/evalscope#122]
**Running this script results in an error. How can I fix it?**
**- script**
```
python -m evalscope.run \
 --model qwen/Qwen2-0.5B-Instruct \
 --template-type qwen \
 --datasets arc 
```

**- error**
```
Generating test split: 169 examples [00:00, 2188.70 examples/s]
Generating dev split: 5 examples [00:00, 998.88 examples/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/evalscope_py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/evalscope_py310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/nfs/10_performance/evalscope/package/evalscope/run.py", line 404, in <module>
    main()
  File "/workspace/nfs/10_performance/evalscope/package/evalscope/run.py", line 398, in main
    run_task(task_cfg)
  File "/workspace/nfs/10_performance/evalscope/package/evalscope/run.py", line 345, in run_task
    evaluator = Evaluator(
  File "/workspace/nfs/10_performance/evalscope/package/evalscope/evaluator/evaluator.py", line 101, in __init__
    self.dataset = self.data_adapter.load(dataset_name_or_path=dataset_name_or_path,
  File "/workspace/nfs/10_performance/evalscope/package/evalscope/benchmarks/data_adapter.py", line 79, in load
    dataset = Benchmark.load(dataset_name=dataset_name_or_path,
  File "/workspace/nfs/10_performance/evalscope/package/evalscope/benchmarks/benchmark.py", line 49, in load
    dataset.split = split
```

**Comment by Jeremy-J-J** [comment]
How is the progress?

**Comment by Yunnglin** [comment]
@Jeremy-J-J pls install from the main branch
```
pip install git+https://github.com/modelscope/evalscope.git@main
```

**Comment by Jeremy-J-J** [comment]
got it, thx
