### ISSUE TITLE
执行cmtb评估示例代码example_eval_mteb.py报错pydantic_core._pydantic_core.ValidationError: 2 validation errors for TaskMetadata

### ISSUE THREAD

**Issue by A-cracker** [modelscope/evalscope#176]
![屏幕截图 2024-11-03 155505](https://github.com/user-attachments/assets/2092ec97-864d-4a05-a1ea-5306a2bf14ed)
(eval-scope) [lzn@localhost examples]$ python example_eval_mteb.py
2024-11-03 15:55:33,394 - evalscope - INFO - ** Args: Task config is provided with dictionary type. **
2024-11-03 15:55:34,085 - datasets - INFO - PyTorch version 2.5.1 available.
2024-11-03 15:55:34,086 - datasets - INFO - Polars version 1.12.0 available.
2024-11-03 15:55:36,497 - evalscope - INFO - Check `mteb` Installed
Traceback (most recent call last):
  File "/home/lzn/ragqa/eval-scope/examples/example_eval_mteb.py", line 100, in <module>
    run_eval()
  File "/home/lzn/ragqa/eval-scope/examples/example_eval_mteb.py", line 96, in run_eval
    run_task(task_cfg=one_stage_task_cfg)
  File "/home/lzn/ragqa/eval-scope/package/evalscope/run.py", line 213, in run_task
    rag_eval_backend_manager.run()
  File "/home/lzn/ragqa/eval-scope/package/evalscope/backend/rag_eval/backend_manager.py", line 70, in run
    self.run_mteb(model_args, eval_args)
  File "/home/lzn/ragqa/eval-scope/package/evalscope/backend/rag_eval/backend_manager.py", line 29, in run_mteb
    from evalscope.backend.rag_eval.cmteb import ModelArguments, EvalArguments
  File "/home/lzn/ragqa/eval-scope/package/evalscope/backend/rag_eval/cmteb/__init__.py", line 1, in <module>
    from evalscope.backend.rag_eval.cmteb.tasks import *
  File "/home/lzn/ragqa/eval-scope/package/evalscope/backend/rag_eval/cmteb/tasks/__init__.py", line 2, in <module>
    from .Clustering import *
  File "/home/lzn/ragqa/eval-scope/package/evalscope/backend/rag_eval/cmteb/tasks/Clustering.py", line 15, in <module>
    class CLSClusteringFastS2S(AbsTaskClusteringFast):
  File "/home/lzn/ragqa/eval-scope/package/evalscope/backend/rag_eval/cmteb/tasks/Clustering.py", line 19, in CLSClusteringFastS2S
    metadata = TaskMetadata(
  File "/home/lzn/anaconda3/envs/eval-scope/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for TaskMetadata
license.`literal['not specified','mit','cc-by-2.0','cc-by-3.0','cc-by-4.0','cc-by-sa-3.0','cc-by-sa-4.0','cc-by-nc-4.0','cc-by-nc-sa-3.0','cc-by-nc-sa-4.0','cc-by-nc-nd-4.0','openrail','openrail++','odc-by','afl-3.0','apache-2.0','cc-by-nd-2.1-jp','cc0-1.0','bsd-3-clause','gpl-3.0','cdla-sharing-1.0','mpl-2.0']`
  Input should be 'not specified', 'mit', 'cc-by-2.0', 'cc-by-3.0', 'cc-by-4.0', 'cc-by-sa-3.0', 'cc-by-sa-4.0', 'cc-by-nc-4.0', 'cc-by-nc-sa-3.0', 'cc-by-nc-sa-4.0', 'cc-by-nc-nd-4.0', 'openrail', 'openrail++', 'odc-by', 'afl-3.0', 'apache-2.0', 'cc-by-nd-2.1-jp', 'cc0-1.0', 'bsd-3-clause', 'gpl-3.0', 'cdla-sharing-1.0' or 'mpl-2.0' [type=literal_error, input_value='Apache-2.0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/literal_error
license.function-before[<lambda>(), str]
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='Apache-2.0', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing

**Comment by chaoStart** [comment]
I have the same problem.Did you  resolve the promblem?
