### ISSUE TITLE
ragas 评测：httpx.ConnectError: All connection attempts failed

### ISSUE THREAD

**Issue by jackqdldd** [modelscope/evalscope#193]
![image](https://github.com/user-attachments/assets/8fab756f-cf1a-4fa1-aeef-56b15320d0f6)

`Traceback (most recent call last):
  File "/home/alg/qdl/rags/evalscope_ragas_eval.py", line 37, in <module>
    run_task(task_cfg=eval_task_cfg)
  File "/home/alg/qdl/evalscope/package/evalscope/run.py", line 213, in run_task
    rag_eval_backend_manager.run()
  File "/home/alg/qdl/evalscope/package/evalscope/backend/rag_eval/backend_manager.py", line 75, in run
    self.run_ragas(testset_args, eval_args)
  File "/home/alg/qdl/evalscope/package/evalscope/backend/rag_eval/backend_manager.py", line 56, in run_ragas
    rag_eval(EvaluationArguments(**eval_args))
  File "/home/alg/qdl/evalscope/package/evalscope/backend/rag_eval/ragas/task_template.py", line 35, in rag_eval
    asyncio.run(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/alg/qdl/evalscope/package/evalscope/backend/rag_eval/ragas/tasks/translate_prompt.py", line 65, in translate_prompts
    await asyncio.gather(
  File "/home/alg/qdl/evalscope/package/evalscope/backend/rag_eval/ragas/tasks/translate_prompt.py", line 45, in translate_prompt
    adapted_prompts = await prompt_user.adapt_prompts(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/ragas/prompt/mixin.py", line 70, in adapt_prompts
    adapted_prompt = await prompt.adapt(language, llm, adapt_instruction)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/ragas/prompt/pydantic_prompt.py", line 242, in adapt
    translated_strings = await translate_statements_prompt.generate(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/ragas/prompt/pydantic_prompt.py", line 130, in generate
    output_single = await self.generate_multiple(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/ragas/prompt/pydantic_prompt.py", line 190, in generate_multiple
    resp = await llm.generate(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/ragas/llms/base.py", line 100, in generate
    result = await agenerate_text_with_retry(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/ragas/llms/base.py", line 220, in agenerate_text
    return await self.langchain_llm.agenerate_prompt(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 796, in agenerate_prompt
    return await self.agenerate(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 756, in agenerate
    raise exceptions[0]
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/langchain_core/language_models/chat_models.py", line 924, in _agenerate_with_cache
    result = await self._agenerate(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/langchain_openai/chat_models/base.py", line 860, in _agenerate
    response = await self.async_client.create(**payload)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1661, in create
    return await self._post(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/_base_client.py", line 1838, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in request
    return await self._request(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/_base_client.py", line 1618, in _request
    return await self._retry_request(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/_base_client.py", line 1665, in _retry_request
    return await self._request(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/_base_client.py", line 1595, in _request
    return await self._retry_request(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/_base_client.py", line 1665, in _retry_request
    return await self._request(
  File "/home/alg/anaconda3/envs/evalscope/lib/python3.10/site-packages/openai/_base_client.py", line 1605, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
`
![image](https://github.com/user-attachments/assets/b8b85e14-b246-48ca-b207-f739f33844fd)

b不知道哪一步报错了

**Comment by jackqdldd** [comment]
看错了
