### ISSUE TITLE
 vllm==0.6.4.post1 evalscope 存在不兼容的情况   perf 报错  modelscope ：  ImportError: cannot import name '_datasets_server' from 'datasets.utils'

### ISSUE THREAD

**Issue by shell-nlp** [modelscope/evalscope#220]
分析发现是 vllm==0.6.4.post1   evalscope   存在不兼容的情况
原理：  vllm==0.6.4.post1 需要 setuptools==75.2.0, 但是 evalscope依赖的modelscope 需要 setuptools==69.X

**Comment by shell-nlp** [comment]
```
2024-11-28 16:21:38,243 - modelscope - INFO - PyTorch version 2.5.1 Found.
2024-11-28 16:21:38,245 - modelscope - INFO - Loading ast index from /home/dev/.cache/modelscope/ast_indexer
2024-11-28 16:21:38,285 - modelscope - INFO - Loading done! Current index file version is 1.13.3, with md5 1cd58d669c1324f88698a03721d23826 and a total number of 972 components indexed
2024-11-28 16:21:40,405 - datasets - INFO - PyTorch version 2.5.1 available.
Traceback (most recent call last):
  File "/home/dev/liuyu/project/gpt_server/tests/test_perf.py", line 2, in <module>
    from evalscope.perf.main import run_perf_benchmark
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/evalscope/perf/main.py", line 6, in <module>
    from evalscope.perf.benchmark import benchmark
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/evalscope/perf/benchmark.py", line 17, in <module>
    from evalscope.perf.plugin.registry import ApiRegistry, DatasetRegistry
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/evalscope/perf/plugin/__init__.py", line 2, in <module>
    from evalscope.perf.plugin.datasets import *
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/evalscope/perf/plugin/datasets/__init__.py", line 2, in <module>
    from evalscope.perf.plugin.datasets.flickr8k import FlickrDatasetPlugin
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/evalscope/perf/plugin/datasets/flickr8k.py", line 5, in <module>
    from modelscope.msdatasets import MsDataset
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/modelscope/msdatasets/__init__.py", line 2, in <module>
    from .ms_dataset import MsDataset
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/modelscope/msdatasets/ms_dataset.py", line 24, in <module>
    from modelscope.msdatasets.utils.hf_datasets_util import \
  File "/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/modelscope/msdatasets/utils/hf_datasets_util.py", line 42, in <module>
    from datasets.utils import _datasets_server, file_utils
ImportError: cannot import name '_datasets_server' from 'datasets.utils' (/home/dev/liuyu/project/gpt_server/.venv/lib/python3.10/site-packages/datasets/utils/__init__.py)
```

**Comment by shell-nlp** [comment]
![image](https://github.com/user-attachments/assets/3ed9185f-fbab-49c5-8dc3-6fa99fcfa8ec)

**Comment by wangxingjun778** [comment]
原因是datasets这个依赖，2.x和3.x版本有breaking change，modelscope中做了限制。
