### ISSUE TITLE
ValueError: No nodes that satisfied the given filer. Try changing the filter.

### ISSUE THREAD

**Issue by cholossi** [modelscope/evalscope#230]
## 问题描述 / Issue Description
直到生成kg前都没问题

## 执行的代码或指令 / Code or Commands Executed
from evalscope.run import run_task
from evalscope.utils.logger import get_logger
from langchain_unstructured import UnstructuredLoader
base_url = "http://127.0.0.1:11434/v1"

generate_testset_task_cfg = {
    "eval_backend": "RAGEval",
    "eval_config": {
        "tool": "RAGAS",
        "testset_generation": {
            "docs": ["/home/zeng/docs/docs.md"],
            "test_size": 10,
            "output_file": r"/home/zeng/outputs/test_generate_result.json",
            "knowledge_graph": r"/home/zeng/outputs/knowledge_graph.json",
            "distribution": {"simple": 0.3, "multi_context": 0.3, "reasoning": 0.4},
            "generator_llm": {
                "model_name":"qwen2.5:7b",
                "api_base":base_url,
            },
            "embeddings": {
                "model_name_or_path": "BAAI/bge-m3",
            },
            "language": "chinese"
        }
    },
}

logger = get_logger()
run_task(task_cfg=generate_testset_task_cfg)

## 错误日志 / Error Log

请粘贴完整的错误日志或控制台输出。 / Please paste the full error log or console output. 例如 / For example:

```
2024-12-05 02:02:58,399 - ragas.testset.transforms.base - WARNING - Property 'themes' already exists in node '716511'. Skipping!
Applying [CosineSimilarityBuilder, OverlapScoreBuilder]:   0%|          | 0/2 [00:00<?, ?it/s]2024-12-05 02:02:58,408 - ragas.testset.transforms.engine - ERROR - unable to apply transformation: axis 1 is out of bounds for array of dimension 1
2024-12-05 02:02:58,464 - evalscope - INFO - Knowledge graph saved to /home/zeng/outputs/knowledge_graph.json
Traceback (most recent call last):
  File "/home/zeng/evalscope_generate/evalscope_ragas.py", line 29, in <module>
    run_task(task_cfg=generate_testset_task_cfg)
  File "/home/zeng/evalscope/evalscope/run.py", line 213, in run_task
    rag_eval_backend_manager.run()
  File "/home/zeng/evalscope/evalscope/backend/rag_eval/backend_manager.py", line 75, in run
    self.run_ragas(testset_args, eval_args)
  File "/home/zeng/evalscope/evalscope/backend/rag_eval/backend_manager.py", line 54, in run_ragas
    generate_testset(TestsetGenerationArguments(**testset_args))
  File "/home/zeng/evalscope/evalscope/backend/rag_eval/ragas/tasks/testset_generation.py", line 225, in generate_testset
    persona_list = get_persona(llm=wrapped_llm, kg=knowledge_graph, language=args.language)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zeng/evalscope/evalscope/backend/rag_eval/ragas/tasks/testset_generation.py", line 179, in get_persona
    return generate_personas_from_kg(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/esr/lib/python3.12/site-packages/ragas/testset/persona.py", line 95, in generate_personas_from_kg
    raise ValueError(
ValueError: No nodes that satisfied the given filer. Try changing the filter.
```

## 运行环境 / Runtime Environment
evalscope==2.0.0
ragas==0.2.6
- 操作系统 / Operating System:
  Ubuntu

**Comment by Yunnglin** [comment]
这块我们在看下，ragas最近版本更新，这些方法都不太稳定，先试一下ragas v0.2.5呢

**Comment by Yunnglin** [comment]
"没有summary_embedding" 是 0.2.5版本吗

**Comment by cholossi** [comment]
> "没有summary_embedding" 是 0.2.5版本吗

0.2.5；0.2.6都是相同的报错，也都没有summary_embedding

**Comment by cholossi** [comment]
> "没有summary_embedding" 是 0.2.5版本吗

找到原因了，在/evalscope/backend/rag_eval/ragas/tasks/testset_generation.py中有一个summary_filter，其中node.properties['page_content']) > 500，将我的node全过滤了
