### ISSUE TITLE
使用压测工具报错 

### ISSUE THREAD

**Issue by yangyu6** [modelscope/evalscope#236]
## 问题描述 / Issue Description

请简要描述您遇到的问题。 / Please briefly describe the issue you encountered.

## 使用的工具 / Tools Used
evalscope                     0.7.2
- [ ] Perf / 模型推理压测工具

## 执行的代码或指令 / Code or Commands Executed

请提供您执行的主要代码或指令。 / Please provide the main code or commands you executed. 例如 / For example:

```python
from evalscope.perf.main import run_perf_benchmark

task_cfg = {"url": "http://10.255.4.2:8000/v1/chat/completions",
            "parallel": 1,
            "model": "/root/.cache/modelscope",
            "number": 15,
            "api": "openai",
            "dataset": "openqa",
            "stream": True,
            "debug": True}
run_perf_benchmark(task_cfg)
```

## 错误日志 / Error Log

请粘贴完整的错误日志或控制台输出。 / Please paste the full error log or console output. 例如 / For example:

```
2024-12-11 18:11:16,049 - evalscope - handler.py - async_wrapper - 19 - ERROR - Exception in async function 'statistic_benchmark_metric_worker': [Errno 30] Read-only file system: '/root'
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/demo2/lib/python3.10/site-packages/evalscope/perf/utils/handler.py", line 17, in async_wrapper
    return await func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/demo2/lib/python3.10/site-packages/evalscope/perf/benchmark.py", line 141, in statistic_benchmark_metric_worker
    result_db_path = get_result_db_path(args.name, args.model)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/demo2/lib/python3.10/site-packages/evalscope/perf/utils/db_util.py", line 97, in get_result_db_path
    os.makedirs(os.path.dirname(result_db_path), exist_ok=True)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/demo2/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/demo2/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/demo2/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/demo2/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/root'
```

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] macOS

- Python版本 / Python Version:
  - [ ] 3.12

## 其他信息 / Additional Information

如果有其他相关信息，请在此处提供。 / If there is any other relevant information, please provide it here.

**Comment by Yunnglin** [comment]
`model`参数看起来输入的不太对，需要是请求的模型名称，比如`gpt-4o`

> "model": "/root/.cache/modelscope",

**Comment by Yunnglin** [comment]
> 由于长时间未收到活动，我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
