### ISSUE TITLE
0.8.1版本下遇见的humaneval数据集测评问题

### ISSUE THREAD

**Issue by WjMessi1** [modelscope/evalscope#250]
## 问题描述 / Issue Description
用代码：

进行原生evalscope测评时，遇见了报错，如下：

<img width="668" alt="e7ec7dfc5abde23f4c909885c5a2f7b" src="https://github.com/user-attachments/assets/92de7a64-d8f9-4506-960b-4cc6083cff09" />

发现是我没有按照步骤下载包，下载好之后再次运行，有报错如下：

<img width="503" alt="1734485427434" src="https://github.com/user-attachments/assets/165843bf-9167-4be2-b46a-e525c3df24cb" />

最终该问题已经解决，发现是execution.py代码的第59行没有正确缩进

<img width="259" alt="1734485786995" src="https://github.com/user-attachments/assets/c3e46441-1458-4762-b3d1-ec6d1dc2dc97" />

## 使用的工具 / Tools Used
- [√] Native / 原生框架
- [ ] Opencompass backend
- [ ] VLMEvalKit backend
- [ ] RAGEval backend
- [ ] Perf / 模型推理压测工具
- [ ] Arena  /竞技场模式

## 执行的代码或指令 / Code or Commands Executed

```bash
evalscope eval --model /data/Qwen/Qwen2.5-32B-Instruct-AWQ --datasets humaneval --limit 5
```

## 错误日志 / Error Log

```
Traceback (most recent call last):
  File "/root/anaconda3/envs/telechat2/bin/evalscope", line 8, in <module>
    sys.exit(run_cmd())
  File "/root/anaconda3/envs/telechat2/lib/python3.9/site-packages/evalscope/cli/cli.py", line 23, in run_cmd
    cmd.execute()
  File "/root/anaconda3/envs/telechat2/lib/python3.9/site-packages/evalscope/cli/start_eval.py", line 31, in execute
    run_task(self.args)
  File "/root/anaconda3/envs/telechat2/lib/python3.9/site-packages/evalscope/run.py", line 36, in run_task
    return run_single_task(task_cfg, run_time)
  File "/root/anaconda3/envs/telechat2/lib/python3.9/site-packages/evalscope/run.py", line 51, in run_single_task
    return evaluate_model(task_cfg, outputs)
  File "/root/anaconda3/envs/telechat2/lib/python3.9/site-packages/evalscope/run.py", line 107, in evaluate_model
    evaluator = create_evaluator(task_cfg, dataset_name, outputs)
  File "/root/anaconda3/envs/telechat2/lib/python3.9/site-packages/evalscope/run.py", line 125, in create_evaluator
    data_adapter = imported_modules['DataAdapterClass'](
  File "/root/anaconda3/envs/telechat2/lib/python3.9/site-packages/evalscope/benchmarks/humaneval/humaneval_adapter.py", line 38, in __init__
    from human_eval.evaluation import check_correctness
  File "/data/Telechat/EVAL/eval/humaneval/human-eval/human_eval/evaluation.py", line 10, in <module>
    from human_eval.execution import check_correctness
  File "/data/Telechat/EVAL/eval/humaneval/human-eval/human_eval/execution.py", line 59
    result.append("passed")
IndentationError: expected an indented block
```

## 运行环境 / Runtime Environment

- 操作系统 / Operating System:
  - [ ] Windows
  - [ ] macOS
  - [√] Ubuntu

- Python版本 / Python Version:
  - [ ] 3.11
  - [ ] 3.10
  - [√] 3.9

## 其他信息 / Additional Information
evalscope版本0.8.1

**Comment by Yunnglin** [comment]
> 感谢你的反馈！我们将关闭此问题。如果您有任何疑问，请随时重新打开它。如果EvalScope对您有所帮助，欢迎给我们点个STAR以示支持，谢谢！
